{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rsdwc2.fullname" . }}
  labels:
    {{- include "rsdwc2.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
